/*
 * SPDX-FileCopyrightText: 2022 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
import { CodegenConfig } from '@graphql-codegen/cli';

const config: CodegenConfig = {
	schema:
		// 'https://raw.githubusercontent.com/Zextras/carbonio-files-ce/develop/core/src/main/resources/api/schema.graphql',
		{
			'https://sw-s03.demo.zextras.io/services/files/graphql': {
				headers: {
					Cookie:
						'ZM_AUTH_TOKEN=0_60f96c2cc79302b40c267f392ff16d478bb77cbd_69643d33363a34306437663135622d363866332d343031362d396530392d6130623063653866303433643b6578703d31333a313637313937323438363139333b747970653d363a7a696d6272613b753d313a613b7469643d393a3531323235383636393b'
				}
			}
		},
	generates: {
		'src/carbonio-files-ui-common/graphql/schema.graphql': {
			plugins: [
				'schema-ast',
				{
					add: {
						content: ['" THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT! "']
					}
				}
			]
		},
		'src/carbonio-files-ui-common/types/graphql/types.ts': {
			schema: 'src/carbonio-files-ui-common/graphql/client-schema.graphql',
			documents: ['src/**/*.graphql'],
			plugins: [
				'typescript',
				'typescript-operations',
				'typed-document-node',
				{
					add: {
						content: [
							'/* eslint-disable camelcase,no-shadow */',
							'// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!',
							"import * as ClientTypes from './client-types'"
						]
					}
				}
			],
			config: {
				defaultScalarType: 'unknown',
				exportFragmentSpreadSubTypes: true,
				mergeFragmentTypes: true,
				nonOptionalTypename: false,
				scalars: {
					DateTime: 'number',
					UploadItem: 'ClientTypes.UploadItem'
				},
				strictScalars: true
			}
		},
		'src/carbonio-files-ui-common/types/graphql/possible-types.ts': {
			schema: 'src/carbonio-files-ui-common/graphql/client-schema.graphql',
			documents: ['src/**/*.graphql'],
			plugins: [
				'fragment-matcher',
				{ add: { content: '// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!' } }
			]
		}
	},
	hooks: {
		afterAllFileWrite:
			'eslint --fix --resolve-plugins-relative-to node_modules/@zextras/carbonio-ui-configs'
	}
};

export default config;
