version = 1
SPDX-PackageName = "carbonio-files-ui"
SPDX-PackageSupplier = "<>"

[[annotations]]
path = "**.json"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = ["THIRDPARTIES", ".nvmrc", ".npmrc", ".husky/**", ".github/**", "CHANGELOG.md", "REUSE.toml"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Zextras <https://www.zextras.com>"
SPDX-License-Identifier = "CC0-1.0"
