/*
 * SPDX-FileCopyrightText: 2026 Zextras <https://www.zextras.com>
 *
 * SPDX-License-Identifier: AGPL-3.0-only
 */
/* eslint-disable @typescript-eslint/ban-types,@typescript-eslint/no-explicit-any */
// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!
import type { GraphQLResolveInfo, GraphQLScalarType, GraphQLScalarTypeConfig } from 'graphql';

export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = {
	[_ in K]?: never;
};
export type Incremental<T> =
	| T
	| { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
export type Omit<T, K extends keyof T> = Pick<T, Exclude<keyof T, K>>;
export type RequireFields<T, K extends keyof T> = Omit<T, K> & { [P in K]-?: NonNullable<T[P]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
	ID: { input: string; output: string };
	String: { input: string; output: string };
	Boolean: { input: boolean; output: boolean };
	Int: { input: number; output: number };
	Float: { input: number; output: number };
	DateTime: { input: number; output: number };
};

export type Account = DistributionList | User;

export type AddedNode = {
	__typename: 'AddedNode';
	added_node: SnapshotNode;
	added_node_type: AddedNodeType;
	created_at: Scalars['DateTime']['output'];
	destination_folder: SnapshotNode;
	id: Scalars['ID']['output'];
	notification_type: NotificationType;
	triggering_user: SnapshotUser;
};

export enum AddedNodeType {
	Copy = 'COPY',
	Create = 'CREATE',
	Move = 'MOVE',
	Upload = 'UPLOAD'
}

export type CollaborationLink = {
	__typename: 'CollaborationLink';
	created_at: Scalars['DateTime']['output'];
	id: Scalars['ID']['output'];
	node: File | Folder;
	permission: SharePermission;
	url: Scalars['String']['output'];
};

export type Config = {
	__typename: 'Config';
	name: Scalars['String']['output'];
	value: Maybe<Scalars['String']['output']>;
};

export type DistributionList = {
	__typename: 'DistributionList';
	id: Scalars['ID']['output'];
	name: Scalars['String']['output'];
	users: Array<Maybe<User>>;
};

export type DistributionListUsersArgs = {
	cursor?: InputMaybe<Scalars['String']['input']>;
	limit: Scalars['Int']['input'];
};

export type File = Node & {
	__typename: 'File';
	cloned_from_version: Maybe<Scalars['Int']['output']>;
	collaboration_links: Array<Maybe<CollaborationLink>>;
	created_at: Scalars['DateTime']['output'];
	creator: User;
	description: Scalars['String']['output'];
	digest: Scalars['String']['output'];
	extension: Maybe<Scalars['String']['output']>;
	flagged: Scalars['Boolean']['output'];
	id: Scalars['ID']['output'];
	keep_forever: Scalars['Boolean']['output'];
	last_editor: Maybe<User>;
	links: Array<Maybe<Link>>;
	mime_type: Scalars['String']['output'];
	name: Scalars['String']['output'];
	owner: Maybe<User>;
	parent: Maybe<File | Folder>;
	permissions: Permissions;
	rootId: Maybe<Scalars['ID']['output']>;
	share: Maybe<Share>;
	shares: Array<Maybe<Share>>;
	size: Scalars['Float']['output'];
	type: NodeType;
	updated_at: Scalars['DateTime']['output'];
	version: Scalars['Int']['output'];
};

export type FileShareArgs = {
	share_target_id: Scalars['ID']['input'];
};

export type FileSharesArgs = {
	cursor?: InputMaybe<Scalars['String']['input']>;
	limit: Scalars['Int']['input'];
	sorts?: InputMaybe<Array<ShareSort>>;
};

export type Folder = Node & {
	__typename: 'Folder';
	children: NodePage;
	collaboration_links: Array<Maybe<CollaborationLink>>;
	created_at: Scalars['DateTime']['output'];
	creator: User;
	description: Scalars['String']['output'];
	flagged: Scalars['Boolean']['output'];
	id: Scalars['ID']['output'];
	last_editor: Maybe<User>;
	links: Array<Maybe<Link>>;
	name: Scalars['String']['output'];
	owner: Maybe<User>;
	parent: Maybe<File | Folder>;
	permissions: Permissions;
	rootId: Maybe<Scalars['ID']['output']>;
	share: Maybe<Share>;
	shares: Array<Maybe<Share>>;
	type: NodeType;
	updated_at: Scalars['DateTime']['output'];
};

export type FolderChildrenArgs = {
	limit: Scalars['Int']['input'];
	page_token?: InputMaybe<Scalars['String']['input']>;
	sort: NodeSort;
};

export type FolderShareArgs = {
	share_target_id: Scalars['ID']['input'];
};

export type FolderSharesArgs = {
	cursor?: InputMaybe<Scalars['String']['input']>;
	limit: Scalars['Int']['input'];
	sorts?: InputMaybe<Array<ShareSort>>;
};

export type Link = {
	__typename: 'Link';
	access_code: Maybe<Scalars['String']['output']>;
	created_at: Scalars['DateTime']['output'];
	description: Maybe<Scalars['String']['output']>;
	expires_at: Maybe<Scalars['DateTime']['output']>;
	id: Scalars['ID']['output'];
	node: File | Folder;
	url: Maybe<Scalars['String']['output']>;
};

export type Mutation = {
	__typename: 'Mutation';
	cloneVersion: File;
	copyNodes: Maybe<Array<File | Folder>>;
	createCollaborationLink: CollaborationLink;
	createFolder: File | Folder;
	createLink: Link;
	createShare: Share;
	deleteAllNodesAndBlobs: Scalars['Boolean']['output'];
	deleteCollaborationLinks: Array<Maybe<Scalars['ID']['output']>>;
	deleteLinks: Array<Maybe<Scalars['ID']['output']>>;
	deleteNodes: Maybe<Array<Scalars['ID']['output']>>;
	deleteShares: Array<Maybe<Scalars['ID']['output']>>;
	deleteVersions: Array<Maybe<Scalars['Int']['output']>>;
	flagNodes: Maybe<Array<Scalars['ID']['output']>>;
	keepVersions: Array<Maybe<Scalars['Int']['output']>>;
	moveNodes: Maybe<Array<File | Folder>>;
	restoreNodes: Maybe<Array<Maybe<File | Folder>>>;
	transferOwnership: File | Folder;
	trashNodes: Maybe<Array<Scalars['ID']['output']>>;
	updateLink: Maybe<Link>;
	updateNode: File | Folder;
	updateShares: Array<Maybe<Share>>;
};

export type MutationCloneVersionArgs = {
	node_id: Scalars['ID']['input'];
	version: Scalars['Int']['input'];
};

export type MutationCopyNodesArgs = {
	destination_id: Scalars['ID']['input'];
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationCreateCollaborationLinkArgs = {
	node_id: Scalars['ID']['input'];
	permission: SharePermission;
};

export type MutationCreateFolderArgs = {
	destination_id: Scalars['String']['input'];
	name: Scalars['String']['input'];
};

export type MutationCreateLinkArgs = {
	access_code?: InputMaybe<Scalars['String']['input']>;
	description?: InputMaybe<Scalars['String']['input']>;
	expires_at?: InputMaybe<Scalars['DateTime']['input']>;
	node_id: Scalars['ID']['input'];
};

export type MutationCreateShareArgs = {
	custom_message?: InputMaybe<Scalars['String']['input']>;
	expires_at?: InputMaybe<Scalars['DateTime']['input']>;
	node_id: Scalars['ID']['input'];
	permission: SharePermission;
	share_target_id: Scalars['ID']['input'];
};

export type MutationDeleteAllNodesAndBlobsArgs = {
	user_id: Scalars['ID']['input'];
};

export type MutationDeleteCollaborationLinksArgs = {
	collaboration_link_ids: Array<Scalars['ID']['input']>;
};

export type MutationDeleteLinksArgs = {
	link_ids: Array<Scalars['ID']['input']>;
};

export type MutationDeleteNodesArgs = {
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationDeleteSharesArgs = {
	node_id: Scalars['ID']['input'];
	share_target_ids: Array<Scalars['ID']['input']>;
};

export type MutationDeleteVersionsArgs = {
	node_id: Scalars['ID']['input'];
	versions?: InputMaybe<Array<Scalars['Int']['input']>>;
};

export type MutationFlagNodesArgs = {
	flag: Scalars['Boolean']['input'];
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationKeepVersionsArgs = {
	keep_forever: Scalars['Boolean']['input'];
	node_id: Scalars['ID']['input'];
	versions: Array<Scalars['Int']['input']>;
};

export type MutationMoveNodesArgs = {
	destination_id: Scalars['ID']['input'];
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationRestoreNodesArgs = {
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationTransferOwnershipArgs = {
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
	user_id: Scalars['ID']['input'];
};

export type MutationTrashNodesArgs = {
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
};

export type MutationUpdateLinkArgs = {
	access_code?: InputMaybe<Scalars['String']['input']>;
	description?: InputMaybe<Scalars['String']['input']>;
	expires_at?: InputMaybe<Scalars['DateTime']['input']>;
	link_id: Scalars['ID']['input'];
};

export type MutationUpdateNodeArgs = {
	description?: InputMaybe<Scalars['String']['input']>;
	flagged?: InputMaybe<Scalars['Boolean']['input']>;
	name?: InputMaybe<Scalars['String']['input']>;
	node_id: Scalars['String']['input'];
};

export type MutationUpdateSharesArgs = {
	expires_at?: InputMaybe<Scalars['DateTime']['input']>;
	node_id: Scalars['ID']['input'];
	permission?: InputMaybe<SharePermission>;
	share_target_ids: Array<Scalars['ID']['input']>;
};

export type NewShare = {
	__typename: 'NewShare';
	created_at: Scalars['DateTime']['output'];
	id: Scalars['ID']['output'];
	node: SnapshotNode;
	notification_type: NotificationType;
	triggering_user: SnapshotUser;
};

export type Node = {
	collaboration_links: Array<Maybe<CollaborationLink>>;
	created_at: Scalars['DateTime']['output'];
	creator: User;
	description: Scalars['String']['output'];
	flagged: Scalars['Boolean']['output'];
	id: Scalars['ID']['output'];
	last_editor: Maybe<User>;
	links: Array<Maybe<Link>>;
	name: Scalars['String']['output'];
	owner: Maybe<User>;
	parent: Maybe<File | Folder>;
	permissions: Permissions;
	rootId: Maybe<Scalars['ID']['output']>;
	share: Maybe<Share>;
	shares: Array<Maybe<Share>>;
	type: NodeType;
	updated_at: Scalars['DateTime']['output'];
};

export type NodeShareArgs = {
	share_target_id: Scalars['ID']['input'];
};

export type NodeSharesArgs = {
	cursor?: InputMaybe<Scalars['String']['input']>;
	limit: Scalars['Int']['input'];
	sorts?: InputMaybe<Array<ShareSort>>;
};

export type NodePage = {
	__typename: 'NodePage';
	nodes: Array<Maybe<File | Folder>>;
	page_token: Maybe<Scalars['String']['output']>;
};

export enum NodeSort {
	LastEditorAsc = 'LAST_EDITOR_ASC',
	LastEditorDesc = 'LAST_EDITOR_DESC',
	NameAsc = 'NAME_ASC',
	NameDesc = 'NAME_DESC',
	OwnerAsc = 'OWNER_ASC',
	OwnerDesc = 'OWNER_DESC',
	SizeAsc = 'SIZE_ASC',
	SizeDesc = 'SIZE_DESC',
	TypeAsc = 'TYPE_ASC',
	TypeDesc = 'TYPE_DESC',
	UpdatedAtAsc = 'UPDATED_AT_ASC',
	UpdatedAtDesc = 'UPDATED_AT_DESC'
}

export enum NodeType {
	Application = 'APPLICATION',
	Audio = 'AUDIO',
	Folder = 'FOLDER',
	Image = 'IMAGE',
	Message = 'MESSAGE',
	Other = 'OTHER',
	Presentation = 'PRESENTATION',
	Root = 'ROOT',
	Spreadsheet = 'SPREADSHEET',
	Text = 'TEXT',
	Video = 'VIDEO'
}

export type Notification =
	| AddedNode
	| NewShare
	| RemovedNode
	| SucceededRecording
	| TransferredOwnership;

export type NotificationPage = {
	__typename: 'NotificationPage';
	last_seen: Scalars['DateTime']['output'];
	notifications: Array<Maybe<Notification>>;
	page_token: Maybe<Scalars['String']['output']>;
	unread: Scalars['Int']['output'];
};

export enum NotificationType {
	AddedNode = 'ADDED_NODE',
	NewShare = 'NEW_SHARE',
	RemovedNode = 'REMOVED_NODE',
	SucceededRecording = 'SUCCEEDED_RECORDING',
	TransferredOwnership = 'TRANSFERRED_OWNERSHIP'
}

export type Permissions = {
	__typename: 'Permissions';
	can_add_version: Scalars['Boolean']['output'];
	can_change_link: Scalars['Boolean']['output'];
	can_change_share: Scalars['Boolean']['output'];
	can_delete: Scalars['Boolean']['output'];
	can_read: Scalars['Boolean']['output'];
	can_read_link: Scalars['Boolean']['output'];
	can_read_share: Scalars['Boolean']['output'];
	can_share: Scalars['Boolean']['output'];
	can_write_file: Scalars['Boolean']['output'];
	can_write_folder: Scalars['Boolean']['output'];
};

export type Query = {
	__typename: 'Query';
	findNodes: Maybe<NodePage>;
	getAccountByEmail: Maybe<Account>;
	getAccountsByEmail: Array<Maybe<Account>>;
	getCollaborationLinks: Array<Maybe<CollaborationLink>>;
	getConfigs: Array<Maybe<Config>>;
	getLinks: Array<Maybe<Link>>;
	getNode: Maybe<File | Folder>;
	getNotifications: Maybe<NotificationPage>;
	getPath: Array<Maybe<File | Folder>>;
	getRootsList: Array<Maybe<Root>>;
	getShare: Maybe<Share>;
	getTransferOwnershipAvailability: Scalars['Boolean']['output'];
	getUserById: Maybe<User>;
	getVersions: Array<Maybe<File>>;
};

export type QueryFindNodesArgs = {
	cascade?: InputMaybe<Scalars['Boolean']['input']>;
	direct_share?: InputMaybe<Scalars['Boolean']['input']>;
	flagged?: InputMaybe<Scalars['Boolean']['input']>;
	folder_id?: InputMaybe<Scalars['String']['input']>;
	keywords?: InputMaybe<Array<Scalars['String']['input']>>;
	limit?: InputMaybe<Scalars['Int']['input']>;
	owner_id?: InputMaybe<Scalars['String']['input']>;
	page_token?: InputMaybe<Scalars['String']['input']>;
	shared_by_me?: InputMaybe<Scalars['Boolean']['input']>;
	shared_with_me?: InputMaybe<Scalars['Boolean']['input']>;
	sort?: InputMaybe<NodeSort>;
	type?: InputMaybe<NodeType>;
};

export type QueryGetAccountByEmailArgs = {
	email: Scalars['String']['input'];
};

export type QueryGetAccountsByEmailArgs = {
	emails: Array<Scalars['String']['input']>;
};

export type QueryGetCollaborationLinksArgs = {
	node_id: Scalars['ID']['input'];
};

export type QueryGetLinksArgs = {
	node_id: Scalars['ID']['input'];
};

export type QueryGetNodeArgs = {
	node_id: Scalars['ID']['input'];
	version?: InputMaybe<Scalars['Int']['input']>;
};

export type QueryGetNotificationsArgs = {
	limit?: InputMaybe<Scalars['Int']['input']>;
	page_token?: InputMaybe<Scalars['String']['input']>;
	update_last_seen: Scalars['Boolean']['input'];
};

export type QueryGetPathArgs = {
	node_id: Scalars['ID']['input'];
};

export type QueryGetShareArgs = {
	node_id: Scalars['ID']['input'];
	share_target_id: Scalars['ID']['input'];
};

export type QueryGetTransferOwnershipAvailabilityArgs = {
	node_ids?: InputMaybe<Array<Scalars['ID']['input']>>;
	user_id: Scalars['ID']['input'];
};

export type QueryGetUserByIdArgs = {
	user_id: Scalars['ID']['input'];
};

export type QueryGetVersionsArgs = {
	node_id: Scalars['ID']['input'];
	versions?: InputMaybe<Array<Scalars['Int']['input']>>;
};

export type RemovedNode = {
	__typename: 'RemovedNode';
	created_at: Scalars['DateTime']['output'];
	id: Scalars['ID']['output'];
	notification_type: NotificationType;
	origin_folder: SnapshotNode;
	removed_node: SnapshotNode;
	removed_node_type: RemovedNodeType;
	triggering_user: SnapshotUser;
};

export enum RemovedNodeType {
	Delete = 'DELETE',
	Move = 'MOVE'
}

export type Root = {
	__typename: 'Root';
	id: Scalars['ID']['output'];
	name: Scalars['String']['output'];
};

export type Share = {
	__typename: 'Share';
	created_at: Scalars['DateTime']['output'];
	expires_at: Maybe<Scalars['DateTime']['output']>;
	node: File | Folder;
	permission: SharePermission;
	share_target: Maybe<SharedTarget>;
};

export enum SharePermission {
	ReadAndShare = 'READ_AND_SHARE',
	ReadAndWrite = 'READ_AND_WRITE',
	ReadOnly = 'READ_ONLY',
	ReadWriteAndShare = 'READ_WRITE_AND_SHARE'
}

export enum ShareSort {
	CreationAsc = 'CREATION_ASC',
	CreationDesc = 'CREATION_DESC',
	ExpirationAsc = 'EXPIRATION_ASC',
	ExpirationDesc = 'EXPIRATION_DESC',
	SharePermissionsAsc = 'SHARE_PERMISSIONS_ASC',
	SharePermissionsDesc = 'SHARE_PERMISSIONS_DESC',
	TargetUserAsc = 'TARGET_USER_ASC',
	TargetUserDesc = 'TARGET_USER_DESC'
}

export type SharedTarget = DistributionList | User;

export type SnapshotNode = {
	__typename: 'SnapshotNode';
	created_at: Scalars['DateTime']['output'];
	name: Scalars['String']['output'];
	node_id: Scalars['ID']['output'];
	owner_id: Maybe<Scalars['ID']['output']>;
	snapshot_node_id: Scalars['ID']['output'];
	type: NodeType;
};

export type SnapshotUser = {
	__typename: 'SnapshotUser';
	email: Scalars['String']['output'];
	full_name: Scalars['String']['output'];
	snapshot_user_id: Scalars['ID']['output'];
	user_id: Scalars['ID']['output'];
};

export type SucceededRecording = {
	__typename: 'SucceededRecording';
	created_at: Scalars['DateTime']['output'];
	id: Scalars['ID']['output'];
	notification_type: NotificationType;
	recording_destination_node: SnapshotNode;
	recording_node: SnapshotNode;
};

export type TransferredOwnership = {
	__typename: 'TransferredOwnership';
	created_at: Scalars['DateTime']['output'];
	id: Scalars['ID']['output'];
	notification_type: NotificationType;
	number_of_nodes: Scalars['Int']['output'];
	receiving_user: SnapshotUser;
	resulting_node: SnapshotNode;
	triggering_user: SnapshotUser;
};

export type User = {
	__typename: 'User';
	email: Scalars['String']['output'];
	full_name: Scalars['String']['output'];
	id: Scalars['ID']['output'];
};

export type ResolverTypeWrapper<T> = Promise<T> | T;

export type ResolverWithResolve<TResult, TParent, TContext, TArgs> = {
	resolve: ResolverFn<TResult, TParent, TContext, TArgs>;
};
export type Resolver<
	TResult,
	TParent = Record<PropertyKey, never>,
	TContext = Record<PropertyKey, never>,
	TArgs = Record<PropertyKey, never>
> =
	| ResolverFn<TResult, TParent, TContext, TArgs>
	| ResolverWithResolve<TResult, TParent, TContext, TArgs>;

export type ResolverFn<TResult, TParent, TContext, TArgs> = (
	parent: TParent,
	args: TArgs,
	context: TContext,
	info: GraphQLResolveInfo
) => Promise<TResult> | TResult;

export type SubscriptionSubscribeFn<TResult, TParent, TContext, TArgs> = (
	parent: TParent,
	args: TArgs,
	context: TContext,
	info: GraphQLResolveInfo
) => AsyncIterable<TResult> | Promise<AsyncIterable<TResult>>;

export type SubscriptionResolveFn<TResult, TParent, TContext, TArgs> = (
	parent: TParent,
	args: TArgs,
	context: TContext,
	info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

export interface SubscriptionSubscriberObject<
	TResult,
	TKey extends string,
	TParent,
	TContext,
	TArgs
> {
	subscribe: SubscriptionSubscribeFn<{ [key in TKey]: TResult }, TParent, TContext, TArgs>;
	resolve?: SubscriptionResolveFn<TResult, { [key in TKey]: TResult }, TContext, TArgs>;
}

export interface SubscriptionResolverObject<TResult, TParent, TContext, TArgs> {
	subscribe: SubscriptionSubscribeFn<any, TParent, TContext, TArgs>;
	resolve: SubscriptionResolveFn<TResult, any, TContext, TArgs>;
}

export type SubscriptionObject<TResult, TKey extends string, TParent, TContext, TArgs> =
	| SubscriptionSubscriberObject<TResult, TKey, TParent, TContext, TArgs>
	| SubscriptionResolverObject<TResult, TParent, TContext, TArgs>;

export type SubscriptionResolver<
	TResult,
	TKey extends string,
	TParent = Record<PropertyKey, never>,
	TContext = Record<PropertyKey, never>,
	TArgs = Record<PropertyKey, never>
> =
	| ((...args: any[]) => SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>)
	| SubscriptionObject<TResult, TKey, TParent, TContext, TArgs>;

export type TypeResolveFn<
	TTypes,
	TParent = Record<PropertyKey, never>,
	TContext = Record<PropertyKey, never>
> = (
	parent: TParent,
	context: TContext,
	info: GraphQLResolveInfo
) => Maybe<TTypes> | Promise<Maybe<TTypes>>;

export type IsTypeOfResolverFn<
	T = Record<PropertyKey, never>,
	TContext = Record<PropertyKey, never>
> = (obj: T, context: TContext, info: GraphQLResolveInfo) => boolean | Promise<boolean>;

export type NextResolverFn<T> = () => Promise<T>;

export type DirectiveResolverFn<
	TResult = Record<PropertyKey, never>,
	TParent = Record<PropertyKey, never>,
	TContext = Record<PropertyKey, never>,
	TArgs = Record<PropertyKey, never>
> = (
	next: NextResolverFn<TResult>,
	parent: TParent,
	args: TArgs,
	context: TContext,
	info: GraphQLResolveInfo
) => TResult | Promise<TResult>;

/** Mapping of union types */
export type ResolversUnionTypes<_RefType extends Record<string, unknown>> = {
	Account: DistributionList | User;
	Notification: AddedNode | NewShare | RemovedNode | SucceededRecording | TransferredOwnership;
	SharedTarget: DistributionList | User;
};

/** Mapping of interface types */
export type ResolversInterfaceTypes<_RefType extends Record<string, unknown>> = {
	Node:
		| (Omit<File, 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'> & {
				collaboration_links: Array<Maybe<_RefType['CollaborationLink']>>;
				links: Array<Maybe<_RefType['Link']>>;
				parent?: Maybe<_RefType['Node']>;
				share?: Maybe<_RefType['Share']>;
				shares: Array<Maybe<_RefType['Share']>>;
		  })
		| (Omit<
				Folder,
				'children' | 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'
		  > & {
				children: _RefType['NodePage'];
				collaboration_links: Array<Maybe<_RefType['CollaborationLink']>>;
				links: Array<Maybe<_RefType['Link']>>;
				parent?: Maybe<_RefType['Node']>;
				share?: Maybe<_RefType['Share']>;
				shares: Array<Maybe<_RefType['Share']>>;
		  });
};

/** Mapping between all available schema types and the resolvers types */
export type ResolversTypes = {
	Account: ResolverTypeWrapper<ResolversUnionTypes<ResolversTypes>['Account']>;
	AddedNode: ResolverTypeWrapper<AddedNode>;
	AddedNodeType: AddedNodeType;
	Boolean: ResolverTypeWrapper<Scalars['Boolean']['output']>;
	CollaborationLink: ResolverTypeWrapper<
		Omit<CollaborationLink, 'node'> & { node: ResolversTypes['Node'] }
	>;
	Config: ResolverTypeWrapper<Config>;
	DateTime: ResolverTypeWrapper<Scalars['DateTime']['output']>;
	DistributionList: ResolverTypeWrapper<DistributionList>;
	File: ResolverTypeWrapper<
		Omit<File, 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'> & {
			collaboration_links: Array<Maybe<ResolversTypes['CollaborationLink']>>;
			links: Array<Maybe<ResolversTypes['Link']>>;
			parent?: Maybe<ResolversTypes['Node']>;
			share?: Maybe<ResolversTypes['Share']>;
			shares: Array<Maybe<ResolversTypes['Share']>>;
		}
	>;
	Float: ResolverTypeWrapper<Scalars['Float']['output']>;
	Folder: ResolverTypeWrapper<
		Omit<Folder, 'children' | 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'> & {
			children: ResolversTypes['NodePage'];
			collaboration_links: Array<Maybe<ResolversTypes['CollaborationLink']>>;
			links: Array<Maybe<ResolversTypes['Link']>>;
			parent?: Maybe<ResolversTypes['Node']>;
			share?: Maybe<ResolversTypes['Share']>;
			shares: Array<Maybe<ResolversTypes['Share']>>;
		}
	>;
	ID: ResolverTypeWrapper<Scalars['ID']['output']>;
	Int: ResolverTypeWrapper<Scalars['Int']['output']>;
	Link: ResolverTypeWrapper<Omit<Link, 'node'> & { node: ResolversTypes['Node'] }>;
	Mutation: ResolverTypeWrapper<Record<PropertyKey, never>>;
	NewShare: ResolverTypeWrapper<NewShare>;
	Node: ResolverTypeWrapper<ResolversInterfaceTypes<ResolversTypes>['Node']>;
	NodePage: ResolverTypeWrapper<
		Omit<NodePage, 'nodes'> & { nodes: Array<Maybe<ResolversTypes['Node']>> }
	>;
	NodeSort: NodeSort;
	NodeType: NodeType;
	Notification: ResolverTypeWrapper<ResolversUnionTypes<ResolversTypes>['Notification']>;
	NotificationPage: ResolverTypeWrapper<
		Omit<NotificationPage, 'notifications'> & {
			notifications: Array<Maybe<ResolversTypes['Notification']>>;
		}
	>;
	NotificationType: NotificationType;
	Permissions: ResolverTypeWrapper<Permissions>;
	Query: ResolverTypeWrapper<Record<PropertyKey, never>>;
	RemovedNode: ResolverTypeWrapper<RemovedNode>;
	RemovedNodeType: RemovedNodeType;
	Root: ResolverTypeWrapper<Root>;
	Share: ResolverTypeWrapper<
		Omit<Share, 'node' | 'share_target'> & {
			node: ResolversTypes['Node'];
			share_target?: Maybe<ResolversTypes['SharedTarget']>;
		}
	>;
	SharePermission: SharePermission;
	ShareSort: ShareSort;
	SharedTarget: ResolverTypeWrapper<ResolversUnionTypes<ResolversTypes>['SharedTarget']>;
	SnapshotNode: ResolverTypeWrapper<SnapshotNode>;
	SnapshotUser: ResolverTypeWrapper<SnapshotUser>;
	String: ResolverTypeWrapper<Scalars['String']['output']>;
	SucceededRecording: ResolverTypeWrapper<SucceededRecording>;
	TransferredOwnership: ResolverTypeWrapper<TransferredOwnership>;
	User: ResolverTypeWrapper<User>;
};

/** Mapping between all available schema types and the resolvers parents */
export type ResolversParentTypes = {
	Account: ResolversUnionTypes<ResolversParentTypes>['Account'];
	AddedNode: AddedNode;
	Boolean: Scalars['Boolean']['output'];
	CollaborationLink: Omit<CollaborationLink, 'node'> & { node: ResolversParentTypes['Node'] };
	Config: Config;
	DateTime: Scalars['DateTime']['output'];
	DistributionList: DistributionList;
	File: Omit<File, 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'> & {
		collaboration_links: Array<Maybe<ResolversParentTypes['CollaborationLink']>>;
		links: Array<Maybe<ResolversParentTypes['Link']>>;
		parent?: Maybe<ResolversParentTypes['Node']>;
		share?: Maybe<ResolversParentTypes['Share']>;
		shares: Array<Maybe<ResolversParentTypes['Share']>>;
	};
	Float: Scalars['Float']['output'];
	Folder: Omit<
		Folder,
		'children' | 'collaboration_links' | 'links' | 'parent' | 'share' | 'shares'
	> & {
		children: ResolversParentTypes['NodePage'];
		collaboration_links: Array<Maybe<ResolversParentTypes['CollaborationLink']>>;
		links: Array<Maybe<ResolversParentTypes['Link']>>;
		parent?: Maybe<ResolversParentTypes['Node']>;
		share?: Maybe<ResolversParentTypes['Share']>;
		shares: Array<Maybe<ResolversParentTypes['Share']>>;
	};
	ID: Scalars['ID']['output'];
	Int: Scalars['Int']['output'];
	Link: Omit<Link, 'node'> & { node: ResolversParentTypes['Node'] };
	Mutation: Record<PropertyKey, never>;
	NewShare: NewShare;
	Node: ResolversInterfaceTypes<ResolversParentTypes>['Node'];
	NodePage: Omit<NodePage, 'nodes'> & { nodes: Array<Maybe<ResolversParentTypes['Node']>> };
	Notification: ResolversUnionTypes<ResolversParentTypes>['Notification'];
	NotificationPage: Omit<NotificationPage, 'notifications'> & {
		notifications: Array<Maybe<ResolversParentTypes['Notification']>>;
	};
	Permissions: Permissions;
	Query: Record<PropertyKey, never>;
	RemovedNode: RemovedNode;
	Root: Root;
	Share: Omit<Share, 'node' | 'share_target'> & {
		node: ResolversParentTypes['Node'];
		share_target?: Maybe<ResolversParentTypes['SharedTarget']>;
	};
	SharedTarget: ResolversUnionTypes<ResolversParentTypes>['SharedTarget'];
	SnapshotNode: SnapshotNode;
	SnapshotUser: SnapshotUser;
	String: Scalars['String']['output'];
	SucceededRecording: SucceededRecording;
	TransferredOwnership: TransferredOwnership;
	User: User;
};

export type AccountResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Account'] = ResolversParentTypes['Account']
> = {
	__resolveType: TypeResolveFn<'DistributionList' | 'User', ParentType, ContextType>;
};

export type AddedNodeResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['AddedNode'] = ResolversParentTypes['AddedNode']
> = {
	added_node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	added_node_type?: Resolver<ResolversTypes['AddedNodeType'], ParentType, ContextType>;
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	destination_folder?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	notification_type?: Resolver<ResolversTypes['NotificationType'], ParentType, ContextType>;
	triggering_user?: Resolver<ResolversTypes['SnapshotUser'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type CollaborationLinkResolvers<
	ContextType = any,
	ParentType extends
		ResolversParentTypes['CollaborationLink'] = ResolversParentTypes['CollaborationLink']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	node?: Resolver<ResolversTypes['Node'], ParentType, ContextType>;
	permission?: Resolver<ResolversTypes['SharePermission'], ParentType, ContextType>;
	url?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};

export type ConfigResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Config'] = ResolversParentTypes['Config']
> = {
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	value?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export interface DateTimeScalarConfig
	extends GraphQLScalarTypeConfig<ResolversTypes['DateTime'], any> {
	name: 'DateTime';
}

export type DistributionListResolvers<
	ContextType = any,
	ParentType extends
		ResolversParentTypes['DistributionList'] = ResolversParentTypes['DistributionList']
> = {
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	users?: Resolver<
		Array<Maybe<ResolversTypes['User']>>,
		ParentType,
		ContextType,
		RequireFields<DistributionListUsersArgs, 'limit'>
	>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type FileResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['File'] = ResolversParentTypes['File']
> = {
	cloned_from_version?: Resolver<Maybe<ResolversTypes['Int']>, ParentType, ContextType>;
	collaboration_links?: Resolver<
		Array<Maybe<ResolversTypes['CollaborationLink']>>,
		ParentType,
		ContextType
	>;
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	creator?: Resolver<ResolversTypes['User'], ParentType, ContextType>;
	description?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	digest?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	extension?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
	flagged?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	keep_forever?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	last_editor?: Resolver<Maybe<ResolversTypes['User']>, ParentType, ContextType>;
	links?: Resolver<Array<Maybe<ResolversTypes['Link']>>, ParentType, ContextType>;
	mime_type?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	owner?: Resolver<Maybe<ResolversTypes['User']>, ParentType, ContextType>;
	parent?: Resolver<Maybe<ResolversTypes['Node']>, ParentType, ContextType>;
	permissions?: Resolver<ResolversTypes['Permissions'], ParentType, ContextType>;
	rootId?: Resolver<Maybe<ResolversTypes['ID']>, ParentType, ContextType>;
	share?: Resolver<
		Maybe<ResolversTypes['Share']>,
		ParentType,
		ContextType,
		RequireFields<FileShareArgs, 'share_target_id'>
	>;
	shares?: Resolver<
		Array<Maybe<ResolversTypes['Share']>>,
		ParentType,
		ContextType,
		RequireFields<FileSharesArgs, 'limit'>
	>;
	size?: Resolver<ResolversTypes['Float'], ParentType, ContextType>;
	type?: Resolver<ResolversTypes['NodeType'], ParentType, ContextType>;
	updated_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	version?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type FolderResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Folder'] = ResolversParentTypes['Folder']
> = {
	children?: Resolver<
		ResolversTypes['NodePage'],
		ParentType,
		ContextType,
		RequireFields<FolderChildrenArgs, 'limit' | 'sort'>
	>;
	collaboration_links?: Resolver<
		Array<Maybe<ResolversTypes['CollaborationLink']>>,
		ParentType,
		ContextType
	>;
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	creator?: Resolver<ResolversTypes['User'], ParentType, ContextType>;
	description?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	flagged?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	last_editor?: Resolver<Maybe<ResolversTypes['User']>, ParentType, ContextType>;
	links?: Resolver<Array<Maybe<ResolversTypes['Link']>>, ParentType, ContextType>;
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	owner?: Resolver<Maybe<ResolversTypes['User']>, ParentType, ContextType>;
	parent?: Resolver<Maybe<ResolversTypes['Node']>, ParentType, ContextType>;
	permissions?: Resolver<ResolversTypes['Permissions'], ParentType, ContextType>;
	rootId?: Resolver<Maybe<ResolversTypes['ID']>, ParentType, ContextType>;
	share?: Resolver<
		Maybe<ResolversTypes['Share']>,
		ParentType,
		ContextType,
		RequireFields<FolderShareArgs, 'share_target_id'>
	>;
	shares?: Resolver<
		Array<Maybe<ResolversTypes['Share']>>,
		ParentType,
		ContextType,
		RequireFields<FolderSharesArgs, 'limit'>
	>;
	type?: Resolver<ResolversTypes['NodeType'], ParentType, ContextType>;
	updated_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type LinkResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Link'] = ResolversParentTypes['Link']
> = {
	access_code?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	description?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
	expires_at?: Resolver<Maybe<ResolversTypes['DateTime']>, ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	node?: Resolver<ResolversTypes['Node'], ParentType, ContextType>;
	url?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export type MutationResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Mutation'] = ResolversParentTypes['Mutation']
> = {
	cloneVersion?: Resolver<
		ResolversTypes['File'],
		ParentType,
		ContextType,
		RequireFields<MutationCloneVersionArgs, 'node_id' | 'version'>
	>;
	copyNodes?: Resolver<
		Maybe<Array<ResolversTypes['Node']>>,
		ParentType,
		ContextType,
		RequireFields<MutationCopyNodesArgs, 'destination_id'>
	>;
	createCollaborationLink?: Resolver<
		ResolversTypes['CollaborationLink'],
		ParentType,
		ContextType,
		RequireFields<MutationCreateCollaborationLinkArgs, 'node_id' | 'permission'>
	>;
	createFolder?: Resolver<
		ResolversTypes['Node'],
		ParentType,
		ContextType,
		RequireFields<MutationCreateFolderArgs, 'destination_id' | 'name'>
	>;
	createLink?: Resolver<
		ResolversTypes['Link'],
		ParentType,
		ContextType,
		RequireFields<MutationCreateLinkArgs, 'node_id'>
	>;
	createShare?: Resolver<
		ResolversTypes['Share'],
		ParentType,
		ContextType,
		RequireFields<MutationCreateShareArgs, 'node_id' | 'permission' | 'share_target_id'>
	>;
	deleteAllNodesAndBlobs?: Resolver<
		ResolversTypes['Boolean'],
		ParentType,
		ContextType,
		RequireFields<MutationDeleteAllNodesAndBlobsArgs, 'user_id'>
	>;
	deleteCollaborationLinks?: Resolver<
		Array<Maybe<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		RequireFields<MutationDeleteCollaborationLinksArgs, 'collaboration_link_ids'>
	>;
	deleteLinks?: Resolver<
		Array<Maybe<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		RequireFields<MutationDeleteLinksArgs, 'link_ids'>
	>;
	deleteNodes?: Resolver<
		Maybe<Array<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		Partial<MutationDeleteNodesArgs>
	>;
	deleteShares?: Resolver<
		Array<Maybe<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		RequireFields<MutationDeleteSharesArgs, 'node_id' | 'share_target_ids'>
	>;
	deleteVersions?: Resolver<
		Array<Maybe<ResolversTypes['Int']>>,
		ParentType,
		ContextType,
		RequireFields<MutationDeleteVersionsArgs, 'node_id'>
	>;
	flagNodes?: Resolver<
		Maybe<Array<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		RequireFields<MutationFlagNodesArgs, 'flag'>
	>;
	keepVersions?: Resolver<
		Array<Maybe<ResolversTypes['Int']>>,
		ParentType,
		ContextType,
		RequireFields<MutationKeepVersionsArgs, 'keep_forever' | 'node_id' | 'versions'>
	>;
	moveNodes?: Resolver<
		Maybe<Array<ResolversTypes['Node']>>,
		ParentType,
		ContextType,
		RequireFields<MutationMoveNodesArgs, 'destination_id'>
	>;
	restoreNodes?: Resolver<
		Maybe<Array<Maybe<ResolversTypes['Node']>>>,
		ParentType,
		ContextType,
		Partial<MutationRestoreNodesArgs>
	>;
	transferOwnership?: Resolver<
		ResolversTypes['Node'],
		ParentType,
		ContextType,
		RequireFields<MutationTransferOwnershipArgs, 'user_id'>
	>;
	trashNodes?: Resolver<
		Maybe<Array<ResolversTypes['ID']>>,
		ParentType,
		ContextType,
		Partial<MutationTrashNodesArgs>
	>;
	updateLink?: Resolver<
		Maybe<ResolversTypes['Link']>,
		ParentType,
		ContextType,
		RequireFields<MutationUpdateLinkArgs, 'link_id'>
	>;
	updateNode?: Resolver<
		ResolversTypes['Node'],
		ParentType,
		ContextType,
		RequireFields<MutationUpdateNodeArgs, 'node_id'>
	>;
	updateShares?: Resolver<
		Array<Maybe<ResolversTypes['Share']>>,
		ParentType,
		ContextType,
		RequireFields<MutationUpdateSharesArgs, 'node_id' | 'share_target_ids'>
	>;
};

export type NewShareResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['NewShare'] = ResolversParentTypes['NewShare']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	notification_type?: Resolver<ResolversTypes['NotificationType'], ParentType, ContextType>;
	triggering_user?: Resolver<ResolversTypes['SnapshotUser'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type NodeResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Node'] = ResolversParentTypes['Node']
> = {
	__resolveType: TypeResolveFn<'File' | 'Folder', ParentType, ContextType>;
};

export type NodePageResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['NodePage'] = ResolversParentTypes['NodePage']
> = {
	nodes?: Resolver<Array<Maybe<ResolversTypes['Node']>>, ParentType, ContextType>;
	page_token?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
};

export type NotificationResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Notification'] = ResolversParentTypes['Notification']
> = {
	__resolveType: TypeResolveFn<
		'AddedNode' | 'NewShare' | 'RemovedNode' | 'SucceededRecording' | 'TransferredOwnership',
		ParentType,
		ContextType
	>;
};

export type NotificationPageResolvers<
	ContextType = any,
	ParentType extends
		ResolversParentTypes['NotificationPage'] = ResolversParentTypes['NotificationPage']
> = {
	last_seen?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	notifications?: Resolver<Array<Maybe<ResolversTypes['Notification']>>, ParentType, ContextType>;
	page_token?: Resolver<Maybe<ResolversTypes['String']>, ParentType, ContextType>;
	unread?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
};

export type PermissionsResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Permissions'] = ResolversParentTypes['Permissions']
> = {
	can_add_version?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_change_link?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_change_share?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_delete?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_read?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_read_link?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_read_share?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_share?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_write_file?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
	can_write_folder?: Resolver<ResolversTypes['Boolean'], ParentType, ContextType>;
};

export type QueryResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Query'] = ResolversParentTypes['Query']
> = {
	findNodes?: Resolver<
		Maybe<ResolversTypes['NodePage']>,
		ParentType,
		ContextType,
		Partial<QueryFindNodesArgs>
	>;
	getAccountByEmail?: Resolver<
		Maybe<ResolversTypes['Account']>,
		ParentType,
		ContextType,
		RequireFields<QueryGetAccountByEmailArgs, 'email'>
	>;
	getAccountsByEmail?: Resolver<
		Array<Maybe<ResolversTypes['Account']>>,
		ParentType,
		ContextType,
		RequireFields<QueryGetAccountsByEmailArgs, 'emails'>
	>;
	getCollaborationLinks?: Resolver<
		Array<Maybe<ResolversTypes['CollaborationLink']>>,
		ParentType,
		ContextType,
		RequireFields<QueryGetCollaborationLinksArgs, 'node_id'>
	>;
	getConfigs?: Resolver<Array<Maybe<ResolversTypes['Config']>>, ParentType, ContextType>;
	getLinks?: Resolver<
		Array<Maybe<ResolversTypes['Link']>>,
		ParentType,
		ContextType,
		RequireFields<QueryGetLinksArgs, 'node_id'>
	>;
	getNode?: Resolver<
		Maybe<ResolversTypes['Node']>,
		ParentType,
		ContextType,
		RequireFields<QueryGetNodeArgs, 'node_id'>
	>;
	getNotifications?: Resolver<
		Maybe<ResolversTypes['NotificationPage']>,
		ParentType,
		ContextType,
		RequireFields<QueryGetNotificationsArgs, 'update_last_seen'>
	>;
	getPath?: Resolver<
		Array<Maybe<ResolversTypes['Node']>>,
		ParentType,
		ContextType,
		RequireFields<QueryGetPathArgs, 'node_id'>
	>;
	getRootsList?: Resolver<Array<Maybe<ResolversTypes['Root']>>, ParentType, ContextType>;
	getShare?: Resolver<
		Maybe<ResolversTypes['Share']>,
		ParentType,
		ContextType,
		RequireFields<QueryGetShareArgs, 'node_id' | 'share_target_id'>
	>;
	getTransferOwnershipAvailability?: Resolver<
		ResolversTypes['Boolean'],
		ParentType,
		ContextType,
		RequireFields<QueryGetTransferOwnershipAvailabilityArgs, 'user_id'>
	>;
	getUserById?: Resolver<
		Maybe<ResolversTypes['User']>,
		ParentType,
		ContextType,
		RequireFields<QueryGetUserByIdArgs, 'user_id'>
	>;
	getVersions?: Resolver<
		Array<Maybe<ResolversTypes['File']>>,
		ParentType,
		ContextType,
		RequireFields<QueryGetVersionsArgs, 'node_id'>
	>;
};

export type RemovedNodeResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['RemovedNode'] = ResolversParentTypes['RemovedNode']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	notification_type?: Resolver<ResolversTypes['NotificationType'], ParentType, ContextType>;
	origin_folder?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	removed_node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	removed_node_type?: Resolver<ResolversTypes['RemovedNodeType'], ParentType, ContextType>;
	triggering_user?: Resolver<ResolversTypes['SnapshotUser'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type RootResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Root'] = ResolversParentTypes['Root']
> = {
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
};

export type ShareResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['Share'] = ResolversParentTypes['Share']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	expires_at?: Resolver<Maybe<ResolversTypes['DateTime']>, ParentType, ContextType>;
	node?: Resolver<ResolversTypes['Node'], ParentType, ContextType>;
	permission?: Resolver<ResolversTypes['SharePermission'], ParentType, ContextType>;
	share_target?: Resolver<Maybe<ResolversTypes['SharedTarget']>, ParentType, ContextType>;
};

export type SharedTargetResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['SharedTarget'] = ResolversParentTypes['SharedTarget']
> = {
	__resolveType: TypeResolveFn<'DistributionList' | 'User', ParentType, ContextType>;
};

export type SnapshotNodeResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['SnapshotNode'] = ResolversParentTypes['SnapshotNode']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	node_id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	owner_id?: Resolver<Maybe<ResolversTypes['ID']>, ParentType, ContextType>;
	snapshot_node_id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	type?: Resolver<ResolversTypes['NodeType'], ParentType, ContextType>;
};

export type SnapshotUserResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['SnapshotUser'] = ResolversParentTypes['SnapshotUser']
> = {
	email?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	full_name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	snapshot_user_id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	user_id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
};

export type SucceededRecordingResolvers<
	ContextType = any,
	ParentType extends
		ResolversParentTypes['SucceededRecording'] = ResolversParentTypes['SucceededRecording']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	notification_type?: Resolver<ResolversTypes['NotificationType'], ParentType, ContextType>;
	recording_destination_node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	recording_node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type TransferredOwnershipResolvers<
	ContextType = any,
	ParentType extends
		ResolversParentTypes['TransferredOwnership'] = ResolversParentTypes['TransferredOwnership']
> = {
	created_at?: Resolver<ResolversTypes['DateTime'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	notification_type?: Resolver<ResolversTypes['NotificationType'], ParentType, ContextType>;
	number_of_nodes?: Resolver<ResolversTypes['Int'], ParentType, ContextType>;
	receiving_user?: Resolver<ResolversTypes['SnapshotUser'], ParentType, ContextType>;
	resulting_node?: Resolver<ResolversTypes['SnapshotNode'], ParentType, ContextType>;
	triggering_user?: Resolver<ResolversTypes['SnapshotUser'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type UserResolvers<
	ContextType = any,
	ParentType extends ResolversParentTypes['User'] = ResolversParentTypes['User']
> = {
	email?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	full_name?: Resolver<ResolversTypes['String'], ParentType, ContextType>;
	id?: Resolver<ResolversTypes['ID'], ParentType, ContextType>;
	__isTypeOf?: IsTypeOfResolverFn<ParentType, ContextType>;
};

export type Resolvers<ContextType = any> = {
	Account?: AccountResolvers<ContextType>;
	AddedNode?: AddedNodeResolvers<ContextType>;
	CollaborationLink?: CollaborationLinkResolvers<ContextType>;
	Config?: ConfigResolvers<ContextType>;
	DateTime?: GraphQLScalarType;
	DistributionList?: DistributionListResolvers<ContextType>;
	File?: FileResolvers<ContextType>;
	Folder?: FolderResolvers<ContextType>;
	Link?: LinkResolvers<ContextType>;
	Mutation?: MutationResolvers<ContextType>;
	NewShare?: NewShareResolvers<ContextType>;
	Node?: NodeResolvers<ContextType>;
	NodePage?: NodePageResolvers<ContextType>;
	Notification?: NotificationResolvers<ContextType>;
	NotificationPage?: NotificationPageResolvers<ContextType>;
	Permissions?: PermissionsResolvers<ContextType>;
	Query?: QueryResolvers<ContextType>;
	RemovedNode?: RemovedNodeResolvers<ContextType>;
	Root?: RootResolvers<ContextType>;
	Share?: ShareResolvers<ContextType>;
	SharedTarget?: SharedTargetResolvers<ContextType>;
	SnapshotNode?: SnapshotNodeResolvers<ContextType>;
	SnapshotUser?: SnapshotUserResolvers<ContextType>;
	SucceededRecording?: SucceededRecordingResolvers<ContextType>;
	TransferredOwnership?: TransferredOwnershipResolvers<ContextType>;
	User?: UserResolvers<ContextType>;
};
